<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>StudentManagement.Infrastructure)</AssemblyName>
    <RootNamespace>StudentManagement.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentManagement.Core\StudentManagement.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repositories\" />
    <Folder Include="Data\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
